server:
  port: 8080
  shutdown: graceful
spring:
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/cars}
    username: ${DATASOURCE_USERNAME:cars_user}
    password: ${DATASOURCE_PASSWORD:cars_password}
    driver-class-name: org.postgresql.Driver
management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
      percentiles:
        "[http.server.requests]": 0.95, 0.99

